# No Clocks, LLC Default `dependabot.yml` Configuration File
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: ".github/workflows"
    schedule:
      interval: "daily"
