services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: base
    container_name: base
    # volumes:
    #   - .:/app
    # working_dir: /app
    # command: tail -f /dev/null
